"""Build frozen GOAL 12 pre-call plan and transparent request artifacts."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
SERVICE_ROOT = SCRIPT_DIR.parent
REPO_ROOT = SERVICE_ROOT.parents[1]
sys.path.insert(0, str(SERVICE_ROOT))

from broker_reports_gate1.gate2_financial_evidence_materialization_contracts import (  # noqa: E402,E501
    sha256_json,
)
from broker_reports_gate1.gate2_financial_evidence_registry import (  # noqa: E402
    Gate2FinancialEvidenceRegistryFactory,
)
from broker_reports_gate1.gate2_financial_semantic_v6_context_v2_1_budget_smoke import (  # noqa: E402,E501
    BUDGET_SMOKE_CONTINUATION_KEY,
    BUDGET_SMOKE_SNAPSHOT_AUTHORITY_KEY,
    Gate2FinancialSemanticV6ContextV21BudgetSmokeSlotProjector,
    build_financial_semantic_v6_context_v2_1_budget_smoke_plan,
)
from broker_reports_gate1.gate2_financial_semantic_v6_context_v2_1_budget_smoke_plan import (  # noqa: E402,E501
    BUDGET_SMOKE_MAXIMUM_PROVIDER_SUBMISSIONS,
    financial_semantic_v6_context_v2_1_budget_smoke_operation_identity,
    resolve_financial_semantic_v6_context_v2_1_budget_smoke_expected_answer,
    validate_financial_semantic_v6_context_v2_1_budget_smoke_plan,
)
from broker_reports_gate1.gate2_financial_semantic_v6_outcome_audit import (  # noqa: E402,E501
    validate_financial_semantic_v6_outcome_audit,
)
from broker_reports_gate1.gate2_financial_semantic_v6_qualification import (  # noqa: E402,E501
    Gate2FinancialSemanticV6QualificationFixtureFactory,
)
from broker_reports_gate1.gate2_model_contracts import (  # noqa: E402
    gate2_provider_profile,
)


REPORT_ROOT = REPO_ROOT / "docs" / "reports" / "2026-07-29"
SAFE_PLAN_PATH = (
    REPORT_ROOT
    / "BROKER_REPORTS_GATE2_CONTEXT_V2_1_BUDGET_MODEL_SMOKE_GOAL12.precall.plan.safe.json"
)
TRANSPARENT_PATH = (
    REPORT_ROOT
    / "BROKER_REPORTS_GATE2_CONTEXT_V2_1_BUDGET_MODEL_SMOKE_GOAL12.precall.transparent.json"
)
PRECALL_TRANSPARENT_SCHEMA_VERSION = (
    "broker_reports_gate2_context_v2_1_budget_smoke_precall_transparent_v1"
)
FACTORY_REQUIRED = (
    "build_context_v2_1_budget_smoke_plan uses only the production GOAL 12 "
    "plan builder and slot projector"
)
FORBIDDEN = (
    "The pre-call artifact builder must not call a provider, execute a slot, "
    "include provider output, credentials, filesystem paths or private "
    "mapping material, or claim that the smoke ran"
)

_FORBIDDEN_ARTIFACT_KEYS = frozenset(
    {
        "api_key",
        "authorization",
        "choice_restoration",
        "credential",
        "credentials",
        "filesystem_path",
        "mapping_receipt",
        "password",
        "private_evidence",
        "private_mapping",
        "provider_output",
        "provider_response",
        "provider_response_id",
        "raw_provider_response",
        "repository_path",
        "secret",
        "source_path",
    }
)
_ABSOLUTE_PATH_RE = re.compile(
    r"(?:^[A-Za-z]:[\\/]|^file://|^/(?:etc|home|mnt|tmp|Users|var)/)"
)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail unless both committed artifacts match exact generated bytes.",
    )
    arguments = parser.parse_args(argv)
    safe_plan, transparent = build_artifacts()
    outputs = {
        SAFE_PLAN_PATH: _json_bytes(safe_plan),
        TRANSPARENT_PATH: _json_bytes(transparent),
    }
    write_or_check_outputs(outputs=outputs, check=arguments.check)
    print(
        json.dumps(
            {
                "status": "passed",
                "mode": "check" if arguments.check else "write",
                "provider_calls_total": 0,
                "safe_plan_file_sha256": _sha256_bytes(
                    outputs[SAFE_PLAN_PATH]
                ),
                "transparent_file_sha256": _sha256_bytes(
                    outputs[TRANSPARENT_PATH]
                ),
            },
            sort_keys=True,
        )
    )
    return 0


def build_artifacts() -> tuple[dict[str, Any], dict[str, Any]]:
    audit_manifest = _read_json(
        SERVICE_ROOT
        / "benchmarks"
        / "gate2_financial_semantic_v6_outcome_audit_v1"
        / "manifest.json"
    )
    historical_manifest = _read_json(
        SERVICE_ROOT
        / "benchmarks"
        / "gate2_financial_semantic_v6"
        / "manifest.json"
    )
    base_manifest = _read_json(
        SERVICE_ROOT
        / "benchmarks"
        / "gate2_financial_successor_v2"
        / "manifest.json"
    )
    semantic_pack = _read_json(
        SERVICE_ROOT
        / "semantic_packs"
        / "broker_reports_financial_semantic_pack.v1.json"
    )
    reason_catalog_v2 = _read_json(
        SERVICE_ROOT
        / "managed_assets"
        / "decision_reasons"
        / "broker_reports_gate2_financial_decision_reason_catalog.v2.json"
    )
    audit = validate_financial_semantic_v6_outcome_audit(
        manifest=audit_manifest,
        historical_manifest=historical_manifest,
        base_manifest=base_manifest,
        semantic_pack=semantic_pack,
        reason_catalog_v2=reason_catalog_v2,
    )
    registry = Gate2FinancialEvidenceRegistryFactory().create()
    fixture = Gate2FinancialSemanticV6QualificationFixtureFactory(
        registry=registry,
        snapshot_authority_key=BUDGET_SMOKE_SNAPSHOT_AUTHORITY_KEY,
        continuation_key=BUDGET_SMOKE_CONTINUATION_KEY,
    ).create(
        manifest=historical_manifest,
        base_manifest=base_manifest,
    )
    plan = build_financial_semantic_v6_context_v2_1_budget_smoke_plan(
        fixture=fixture,
        outcome_audit_manifest=audit_manifest,
        registry=registry,
    )
    validate_financial_semantic_v6_context_v2_1_budget_smoke_plan(plan)
    safe_plan = plan.to_safe_dict()
    semantic_cases = {
        item.case_id: item for item in fixture.semantic_cases
    }
    projector = (
        Gate2FinancialSemanticV6ContextV21BudgetSmokeSlotProjector(
            registry=registry
        )
    )
    transparent_slots: list[dict[str, Any]] = []
    for slot in plan.slots:
        case = semantic_cases[slot.case_id]
        provider_profile = gate2_provider_profile(
            slot.provider_profile_id
        )
        projection = projector(
            case=case,
            provider_profile=provider_profile,
            exact_model_id=slot.exact_model_id,
            request_profile=slot.request_profile,
            parameters=slot.parameters,
        )
        expected_answer = (
            resolve_financial_semantic_v6_context_v2_1_budget_smoke_expected_answer(
                plan=plan,
                slot=slot,
                fixture=fixture,
                outcome_audit_manifest=audit_manifest,
            )
        )
        operation_identity = (
            financial_semantic_v6_context_v2_1_budget_smoke_operation_identity(
                plan=plan,
                slot=slot,
            )
        )
        _validate_projection(
            slot=slot,
            case=case,
            provider_profile=provider_profile,
            projection=projection,
            expected_answer=expected_answer,
            operation_identity=operation_identity,
        )
        transparent_slots.append(
            {
                "ordinal": slot.ordinal,
                "slot_id": slot.slot_id,
                "provider": {
                    "provider_profile_id": slot.provider_profile_id,
                    "provider_profile_revision": (
                        slot.provider_profile_revision
                    ),
                    "provider_id": slot.provider_id,
                    "provider_adapter_id": slot.provider_adapter_id,
                    "provider_adapter_version": (
                        slot.provider_adapter_version
                    ),
                },
                "model_identity": {
                    "requested_model_selector": slot.exact_model_id,
                    "identity_kind": slot.model_identity_kind,
                    "immutable_model_id_proven": (
                        slot.immutable_model_id_proven
                    ),
                    "caveat": slot.model_identity_caveat,
                },
                "case": {
                    "case_id": slot.case_id,
                    "taxonomy_state": slot.taxonomy_state,
                },
                "request_profile": slot.request_profile,
                "parameters": slot.parameters.to_dict(),
                "operation_identity": operation_identity,
                "exact_model_visible_request": copy.deepcopy(
                    projection.sealed_request.model_visible_request
                ),
                "exact_final_prepared_request": copy.deepcopy(
                    asdict(projection.prepared_request)
                ),
                "exact_provider_visible_schema": copy.deepcopy(
                    projection.prepared_request.provider_visible_schema
                ),
                "audited_expected_answer": copy.deepcopy(
                    expected_answer
                ),
                "hashes": {
                    "sealed_request_hash": slot.sealed_request_hash,
                    "sealed_request_receipt_integrity_hash": (
                        slot.sealed_request_receipt_integrity_hash
                    ),
                    "model_visible_request_hash": (
                        slot.model_visible_request_hash
                    ),
                    "canonical_schema_hash": (
                        slot.canonical_schema_hash
                    ),
                    "prepared_request_hash": (
                        slot.prepared_request_hash
                    ),
                    "provider_visible_schema_hash": (
                        slot.provider_visible_schema_hash
                    ),
                    "expected_answer_hash": slot.expected_answer_hash,
                    "operation_identity_sha256": _sha256_text(
                        operation_identity
                    ),
                    "slot_integrity_hash": slot.integrity_hash,
                },
                "execution_accounting": {
                    "provider_calls_total": 0,
                    "provider_submissions_total": 0,
                    "provider_responses_total": 0,
                    "retry_total": 0,
                    "repair_total": 0,
                    "fallback_total": 0,
                },
                "status": "preflight_not_executed",
            }
        )
    transparent_material = {
        "schema_version": PRECALL_TRANSPARENT_SCHEMA_VERSION,
        "policy_version": plan.policy_version,
        "status": "preflight_not_executed",
        "frozen": True,
        "active": False,
        "transport_executed": False,
        "contains_customer_data": False,
        "synthetic_evidence_only": True,
        "plan_integrity_hash": plan.integrity_hash,
        "outcome_audit": audit.safe_summary(),
        "slots_total": len(transparent_slots),
        "slots": transparent_slots,
        "execution_accounting": {
            "planned_slots_total": len(plan.slots),
            "maximum_provider_submissions_total": (
                BUDGET_SMOKE_MAXIMUM_PROVIDER_SUBMISSIONS
            ),
            "provider_calls_total": 0,
            "provider_submissions_total": 0,
            "provider_responses_total": 0,
            "retry_total": 0,
            "repair_total": 0,
            "fallback_total": 0,
        },
        "production_admissions": [],
    }
    transparent = {
        **transparent_material,
        "integrity_sha256": sha256_json(transparent_material),
    }
    _validate_artifacts(
        safe_plan=safe_plan,
        transparent=transparent,
    )
    return safe_plan, transparent


def write_or_check_outputs(
    *,
    outputs: dict[Path, bytes],
    check: bool,
) -> None:
    for path, expected in outputs.items():
        if check:
            actual = path.read_bytes() if path.is_file() else None
            if actual != expected:
                raise SystemExit(
                    f"context_v2_1_budget_smoke_precall_drift:{path.name}"
                )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)


def _validate_projection(
    *,
    slot: Any,
    case: Any,
    provider_profile: Any,
    projection: Any,
    expected_answer: dict[str, Any],
    operation_identity: str,
) -> None:
    sealed_request = projection.sealed_request
    prepared_request = projection.prepared_request
    canonical_schema = (
        case.choice_contract.context_v2_1_response_profile
        .canonical_schema()
    )
    if (
        sha256_json(asdict(sealed_request))
        != slot.sealed_request_hash
        or sealed_request.sealed_request_receipt.integrity_hash
        != slot.sealed_request_receipt_integrity_hash
        or sealed_request.sealed_request_receipt.model_visible_request_hash
        != slot.model_visible_request_hash
        or sha256_json(canonical_schema) != slot.canonical_schema_hash
        or sha256_json(asdict(prepared_request))
        != slot.prepared_request_hash
        or sha256_json(prepared_request.provider_visible_schema)
        != slot.provider_visible_schema_hash
        or sha256_json(expected_answer) != slot.expected_answer_hash
        or not prepared_request.context_v2_1_budget_smoke_contract_is_bound(
            canonical_schema=canonical_schema,
            provider_profile=provider_profile,
            model_visible_request=sealed_request.model_visible_request,
            exact_model_id=slot.exact_model_id,
            operation_identity=operation_identity,
        )
    ):
        raise ValueError(
            "context_v2_1_budget_smoke_precall_projection_invalid"
        )


def _validate_artifacts(
    *,
    safe_plan: dict[str, Any],
    transparent: dict[str, Any],
) -> None:
    transparent_material = copy.deepcopy(transparent)
    supplied_integrity = transparent_material.pop(
        "integrity_sha256",
        None,
    )
    if (
        safe_plan.get("status") != "frozen_preflight_not_executed"
        or safe_plan.get("transport_executed") is not False
        or safe_plan.get("execution_accounting", {}).get(
            "provider_submissions_total"
        )
        != 0
        or transparent.get("status") != "preflight_not_executed"
        or transparent.get("transport_executed") is not False
        or transparent.get("slots_total")
        != BUDGET_SMOKE_MAXIMUM_PROVIDER_SUBMISSIONS
        or transparent.get("execution_accounting", {}).get(
            "provider_calls_total"
        )
        != 0
        or transparent.get("execution_accounting", {}).get(
            "provider_submissions_total"
        )
        != 0
        or supplied_integrity != sha256_json(transparent_material)
        or _recursive_keys(transparent) & _FORBIDDEN_ARTIFACT_KEYS
        or any(
            _ABSOLUTE_PATH_RE.search(value)
            for value in _recursive_strings(transparent)
        )
    ):
        raise ValueError(
            "context_v2_1_budget_smoke_precall_artifact_invalid"
        )


def _recursive_keys(value: Any) -> set[str]:
    if isinstance(value, dict):
        return {
            str(key)
            for key in value
        } | {
            nested
            for child in value.values()
            for nested in _recursive_keys(child)
        }
    if isinstance(value, (list, tuple)):
        return {
            nested
            for child in value
            for nested in _recursive_keys(child)
        }
    return set()


def _recursive_strings(value: Any) -> tuple[str, ...]:
    found: list[str] = []

    def visit(item: Any) -> None:
        if isinstance(item, str):
            found.append(item)
        elif isinstance(item, dict):
            for child in item.values():
                visit(child)
        elif isinstance(item, (list, tuple)):
            for child in item:
                visit(child)

    visit(value)
    return tuple(found)


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"json_object_required:{path.name}")
    return value


def _json_bytes(value: dict[str, Any]) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            indent=2,
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha256_text(value: str) -> str:
    return _sha256_bytes(value.encode("utf-8"))


if __name__ == "__main__":
    raise SystemExit(main())
