from __future__ import annotations

import base64
import hashlib
import io
import re
import zipfile
from datetime import datetime, timezone
from typing import Protocol
from uuid import uuid4

from docx import Document
from docx.shared import Pt

from stage2_stt.config import SttConfig
from stage2_stt.contracts import MessageDocxExportRequestV1, MessageDocxExportResultV1


FACTORY_REQUIRED = "DocxExportAdapterFactory.create is the only production DOCX renderer entrypoint"
FORBIDDEN = "Route handlers must not call python-docx directly"

DOCX_CONTENT_TYPE = (
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
)
MAX_FILENAME_STEM = 80
SCAN_PARTS = (
    "word/document.xml",
    "docProps/core.xml",
    "docProps/app.xml",
    "word/_rels/document.xml.rels",
    "_rels/.rels",
)
FORBIDDEN_MARKERS = (
    "authorization",
    "bearer ",
    "cookie",
    "set-cookie",
    "stage2_",
    "lemonfox",
    "openai_api_key",
    "x-stage2-internal-token",
    "raw_provider",
    "provider_payload",
    "verbose_json",
    "http://stage2-stt",
    "stage2-stt:8080",
    "transcript_with_speakers",
    "copy response",
    "regenerate response",
    "good response",
    "bad response",
    "continue response",
    "previous-message-sentinel",
    "next-message-sentinel",
    "toolbar-control-sentinel",
)


class MessageDocxExportError(RuntimeError):
    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.message = message
        super().__init__(f"{code}: {message}")


class DocxExportAdapter(Protocol):
    def render(self, request: MessageDocxExportRequestV1, *, exported_at: datetime) -> bytes:
        ...


class DocxExportAdapterFactory:
    def create(self) -> DocxExportAdapter:
        return PythonDocxExportAdapter()


class PythonDocxExportAdapter:
    def render(self, request: MessageDocxExportRequestV1, *, exported_at: datetime) -> bytes:
        document = Document()
        document.core_properties.title = "Exported Assistant Message"
        document.core_properties.subject = "OpenWebUI message-level DOCX export"
        document.core_properties.author = "STT v2 extension layer"
        document.add_heading("Exported Assistant Message", level=1)

        metadata = _metadata_rows(request, exported_at)
        if metadata:
            table = document.add_table(rows=0, cols=2)
            table.style = "Table Grid"
            for label, value in metadata:
                cells = table.add_row().cells
                cells[0].text = label
                cells[1].text = value
            document.add_paragraph("")

        source_text = request.message_markdown or request.message_text
        _render_simple_markdown(document, source_text)
        document.add_paragraph("")
        footer = document.add_paragraph()
        footer.add_run("Generated by STT v2 extension layer").italic = True

        buffer = io.BytesIO()
        document.save(buffer)
        return buffer.getvalue()


class MessageDocxExportService:
    def __init__(
        self,
        *,
        config: SttConfig,
        adapter: DocxExportAdapter | None = None,
    ) -> None:
        self.config = config
        self.adapter = adapter or DocxExportAdapterFactory().create()

    def export(self, request: MessageDocxExportRequestV1) -> MessageDocxExportResultV1:
        self._validate_request(request)
        exported_at = datetime.now(timezone.utc)
        try:
            payload = self.adapter.render(request, exported_at=exported_at)
        except MessageDocxExportError:
            raise
        except Exception as exc:
            raise MessageDocxExportError(
                "message_docx_generation_failed",
                "DOCX generation failed",
            ) from exc

        max_docx_bytes = self.config.message_docx_max_docx_mb * 1024 * 1024
        if len(payload) > max_docx_bytes:
            raise MessageDocxExportError(
                "message_docx_message_too_large",
                "Generated DOCX exceeds the configured base64 delivery limit",
            )
        _scan_generated_docx(payload)

        checksum = hashlib.sha256(payload).hexdigest()
        return MessageDocxExportResultV1(
            export_id=f"docx-{uuid4().hex}",
            filename=_filename_for_request(request, exported_at),
            content_type=DOCX_CONTENT_TYPE,
            size_bytes=len(payload),
            checksum_sha256=checksum,
            delivery="base64",
            download_payload_base64=base64.b64encode(payload).decode("ascii"),
            download_url=None,
            file_id=None,
            warnings=[],
        )

    def _validate_request(self, request: MessageDocxExportRequestV1) -> None:
        if request.message_role != "assistant":
            raise MessageDocxExportError(
                "message_docx_unsupported_role",
                "Only assistant messages can be exported to DOCX in MVP",
            )
        if not request.message_text or not request.message_text.strip():
            raise MessageDocxExportError(
                "message_docx_empty_message",
                "Selected assistant message is empty",
            )
        if len(request.message_text) > self.config.message_docx_max_message_chars:
            raise MessageDocxExportError(
                "message_docx_message_too_large",
                "Selected assistant message exceeds the configured DOCX export limit",
            )
        if not request.source:
            raise MessageDocxExportError(
                "message_docx_no_safe_source",
                "DOCX export request does not identify a safe message source",
            )
        source_path = request.safe_metadata.source_url_path
        if source_path and not source_path.startswith("/"):
            raise MessageDocxExportError(
                "message_docx_no_safe_source",
                "DOCX export source path must be a relative application path",
            )
        if _contains_forbidden_marker(request.message_text):
            raise MessageDocxExportError(
                "message_docx_no_leak_check_failed",
                "Selected assistant message contains forbidden internal markers",
            )


def _metadata_rows(
    request: MessageDocxExportRequestV1,
    exported_at: datetime,
) -> list[tuple[str, str]]:
    metadata = request.safe_metadata
    rows = [("Export time", exported_at.isoformat())]
    if request.options.include_chat_title and metadata.chat_title:
        rows.append(("Chat title", _safe_metadata_value(metadata.chat_title)))
    if request.options.include_model_name and metadata.model_name:
        rows.append(("Model", _safe_metadata_value(metadata.model_name)))
    if request.options.include_timestamp and metadata.message_timestamp:
        rows.append(("Message time", _safe_metadata_value(metadata.message_timestamp)))
    if metadata.result_ref:
        rows.append(("Result reference", _safe_metadata_value(metadata.result_ref)))
    if metadata.source_url_path:
        rows.append(("Source", _safe_metadata_value(metadata.source_url_path)))
    return [(label, value) for label, value in rows if value]


def _render_simple_markdown(document: Document, text: str) -> None:
    in_code = False
    code_lines: list[str] = []
    for raw_line in str(text or "").replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw_line.rstrip()
        if line.strip().startswith("```"):
            if in_code:
                _add_code_block(document, code_lines)
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        stripped = line.strip()
        if not stripped:
            document.add_paragraph("")
            continue
        heading = re.match(r"^(#{1,3})\s+(.+)$", stripped)
        if heading:
            level = min(len(heading.group(1)) + 1, 4)
            document.add_heading(_strip_inline_markdown(heading.group(2)), level=level)
            continue
        bullet = re.match(r"^[-*+]\s+(.+)$", stripped)
        if bullet:
            document.add_paragraph(_strip_inline_markdown(bullet.group(1)), style="List Bullet")
            continue
        numbered = re.match(r"^\d+[.)]\s+(.+)$", stripped)
        if numbered:
            document.add_paragraph(
                _strip_inline_markdown(numbered.group(1)),
                style="List Number",
            )
            continue
        document.add_paragraph(_strip_inline_markdown(stripped))
    if in_code and code_lines:
        _add_code_block(document, code_lines)


def _add_code_block(document: Document, lines: list[str]) -> None:
    if not lines:
        return
    paragraph = document.add_paragraph()
    run = paragraph.add_run("\n".join(lines))
    run.font.name = "Courier New"
    run.font.size = Pt(9)


def _strip_inline_markdown(text: str) -> str:
    value = str(text or "")
    value = re.sub(r"`([^`]+)`", r"\1", value)
    value = re.sub(r"\*\*([^*]+)\*\*", r"\1", value)
    value = re.sub(r"\*([^*]+)\*", r"\1", value)
    value = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1 (\2)", value)
    return value.strip()


def _filename_for_request(
    request: MessageDocxExportRequestV1,
    exported_at: datetime,
) -> str:
    seed = request.safe_metadata.chat_title or request.message_text.splitlines()[0]
    stem = _sanitize_filename_stem(seed) or "message-export"
    timestamp = exported_at.strftime("%Y%m%d-%H%M%S")
    return f"{stem}-{timestamp}.docx"


def _sanitize_filename_stem(value: str) -> str:
    stem = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', " ", str(value or ""))
    stem = re.sub(r"\s+", " ", stem).strip(" .")
    if len(stem) > MAX_FILENAME_STEM:
        stem = stem[:MAX_FILENAME_STEM].rstrip(" .")
    return stem


def _safe_metadata_value(value: str) -> str:
    cleaned = str(value or "").strip()
    if _contains_forbidden_marker(cleaned):
        raise MessageDocxExportError(
            "message_docx_no_leak_check_failed",
            "DOCX metadata contains forbidden internal markers",
        )
    return cleaned


def _scan_generated_docx(payload: bytes) -> None:
    try:
        with zipfile.ZipFile(io.BytesIO(payload)) as archive:
            for part in SCAN_PARTS:
                if part not in archive.namelist():
                    continue
                text = archive.read(part).decode("utf-8", errors="ignore")
                if _contains_forbidden_marker(text):
                    raise MessageDocxExportError(
                        "message_docx_no_leak_check_failed",
                        f"Generated DOCX contains forbidden marker in {part}",
                    )
    except zipfile.BadZipFile as exc:
        raise MessageDocxExportError(
            "message_docx_generation_failed",
            "Generated DOCX is not a valid ZIP package",
        ) from exc


def _contains_forbidden_marker(text: str) -> bool:
    lowered = str(text or "").lower()
    return any(marker in lowered for marker in FORBIDDEN_MARKERS)
